PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX leader: <http://www.monarchinitiative.org/MONARCH_cliqueLeader>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# If ?s is a better leader than ?o, delete outgoing equivalentClass links from ?o
DELETE {
?o owl:equivalentClass ?o2 .
}
WHERE {
?s owl:equivalentClass ?o .
?o owl:equivalentClass ?o2 .
FILTER(isIRI(?s))
FILTER(isIRI(?o))
FILTER(isIRI(?o2))
OPTIONAL {
    ?s leader: ?sleader .
}
OPTIONAL {
    ?o leader: ?oleader .
}
BIND(COALESCE(SAMETERM(?sleader, "true"^^xsd:), false) AS ?sleaderbool)
BIND(COALESCE(SAMETERM(?oleader, "true"^^xsd:), false) AS ?oleaderbool)
BIND(COALESCE((
    STRSTARTS(STR(?s), "http://www.ncbi.nlm.nih.gov/gene/") ||
    STRSTARTS(STR(?s), "http://www.ncbi.nlm.nih.gov/pubmed/") ||
    STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/NCBITaxon_") ||
    STRSTARTS(STR(?s), "http://identifiers.org/ensembl/") ||
    STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/OMIM_") ||
    STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/DOID_") ||
    STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/Orphanet_") ||
    STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/HP_") ||
    STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/MP_") ||
    STRSTARTS(STR(?s), "http://purl.obolibrary.org/obo/ZP_")), false)
    AS ?spriorityprefix)
BIND(COALESCE((
    STRSTARTS(STR(?o), "http://www.ncbi.nlm.nih.gov/gene/") ||
    STRSTARTS(STR(?o), "http://www.ncbi.nlm.nih.gov/pubmed/") ||
    STRSTARTS(STR(?o), "http://purl.obolibrary.org/obo/NCBITaxon_") ||
    STRSTARTS(STR(?o), "http://identifiers.org/ensembl/") ||
    STRSTARTS(STR(?o), "http://purl.obolibrary.org/obo/OMIM_") ||
    STRSTARTS(STR(?o), "http://purl.obolibrary.org/obo/DOID_") ||
    STRSTARTS(STR(?o), "http://purl.obolibrary.org/obo/Orphanet_") ||
    STRSTARTS(STR(?o), "http://purl.obolibrary.org/obo/HP_") ||
    STRSTARTS(STR(?o), "http://purl.obolibrary.org/obo/MP_") ||
    STRSTARTS(STR(?o), "http://purl.obolibrary.org/obo/ZP_")), false)
    AS ?opriorityprefix)
FILTER(
    (?sleaderbool && !?oleaderbool) || 
    (
        ((?sleaderbool && ?oleaderbool) || (!?sleaderbool && !?oleaderbool)) && 
        (
            (?spriorityprefix && !?opriorityprefix) ||
            (
                ((?spriorityprefix && ?opriorityprefix) || (!?spriorityprefix && !?opriorityprefix)) && 
                (
                    (isIRI(?s) && isBlank(?o)) || 
                    (
                        ((isIRI(?s) && isIRI(?o)) || (isBlank(?s) && isBlank(?o))) && (STR(?s) < STR(?o))
                    )
                )
            )
        )
    )
)
}
